### ISSUE TITLE
conjure-up still not working

### ISSUE THREAD

**Issue by babatundebusari** [Ubuntu-Solutions-Engineering/conjure-up#12]
I have reinstalled another Ubuntu 16.04 LTS and my MAAS server is `MAAS Version 1.9.1+bzr4543-0ubuntu2 (trusty1)`

After running `conjure-up openstack`
here is what i get 

```
ubuntu@ubuntu102:~$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1298, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/ubuntui/views/error.py", line 41, in cancel
    raise SystemExit("Install exited because of error.")
SystemExit: Install exited because of error.
Install exited because of error.
ubuntu@ubuntu102:~$ juju list-controllers
CONTROLLER  MODEL  USER  SERVER

ubuntu@ubuntu102:~$
```

while the command `conjure-up openstack` is running, took screenshot of top processes

<img width="1822" alt="screen shot 2016-05-07 at 3 33 58 am" src="https://cloud.githubusercontent.com/assets/6054104/15090866/d0754920-1404-11e6-90d8-de360da99816.png">

when the error occurred, took another screenshot of top processes

<img width="1815" alt="screen shot 2016-05-07 at 3 37 04 am" src="https://cloud.githubusercontent.com/assets/6054104/15090872/06a86450-1405-11e6-99ca-35d51f97337c.png">

and the screenshot of the error message

<img width="1409" alt="screen shot 2016-05-07 at 3 37 54 am" src="https://cloud.githubusercontent.com/assets/6054104/15090874/1b9f3438-1405-11e6-8bed-4486359e29f8.png">

**Comment by battlemidget** [comment]
You only need to enter the IP address and the apikey, not the full URL

**Comment by babatundebusari** [comment]
still same error messages

```
ubuntu@ubuntu102:~$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1298, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/ubuntui/views/error.py", line 41, in cancel
    raise SystemExit("Install exited because of error.")
SystemExit: Install exited because of error.
Install exited because of error.
ubuntu@ubuntu102:~$ juju list-controllers
CONTROLLER  MODEL  USER  SERVER

ubuntu@ubuntu102:~$
```

<img width="1287" alt="screen shot 2016-05-07 at 3 07 29 pm" src="https://cloud.githubusercontent.com/assets/6054104/15094009/9c34f424-1465-11e6-8681-6ef1ec03cf6c.png">

**Comment by babatundebusari** [comment]
i have tried different installation

`Openstack with Nova-LXD` and `Openstack Autopilot`

all failing with same error

**Comment by babatundebusari** [comment]
removed conjure-up and lxd and started again with new install of only conjure-up 

same result

<img width="1290" alt="screen shot 2016-05-07 at 3 43 55 pm" src="https://cloud.githubusercontent.com/assets/6054104/15094169/9f224ba0-146a-11e6-8fa2-7193fbea8fbd.png">
<img width="1831" alt="screen shot 2016-05-07 at 3 43 44 pm" src="https://cloud.githubusercontent.com/assets/6054104/15094170/9f24a9cc-146a-11e6-8fcd-43725d29bd80.png">
<img width="1836" alt="screen shot 2016-05-07 at 3 39 42 pm" src="https://cloud.githubusercontent.com/assets/6054104/15094171/9f26052e-146a-11e6-8fa8-2a7cea689488.png">


even after conjure-up openstack fails, the process is still running in the background

PLEASE tell me what am doing wrong

**Comment by battlemidget** [comment]
OpenStack with Nova LXD doesn't user MAAS at all so not sure why you're getting the same error. You are probably reusing the same controller. Juju list-controllers and then juju kill-controller name-ofcontroller, then rerun conjure-up and pick the LXD option

**Comment by babatundebusari** [comment]
ok fine but what about openstack autopilot option?

You just ignored all errors for that because i mentioned i tried lxd option
as well? Am just reporting that am trying everything and nothing is working

**Comment by battlemidget** [comment]
email me the latest login for your maas server and ill try to reproduce
